---
- name: Install host-specific components
  yum: name="{{ item }}" state=present
  with_items:
    - php
    - httpd

- name: Prep for ganglia-web
  shell: "{{ item }}"
  with_items:
    - mkdir -p /var/lib/ganglia/rrds
    - chown nobody:nobody /var/lib/ganglia/rrds

- name: Get ganglia-web source
  get_url: dest="/tmp" url="{{ web_ganglia_url }}"

- name: Extract source
  shell: tar -zxf "{{ web_ganglia_pkg_full }}"
  args:
    chdir: "/tmp"

# THis is a hack, issue with ansible? - https://github.com/ansible/ansible/issues/14341
- name: Copy configured Makefile
  copy: src="./roles/ganglia/files/Makefile" dest={{ web_ganglia_build_dir }}

- name: Configure, compile, install
  shell: make install
  args:
    chdir: "{{ web_ganglia_build_dir }}"

- name: Enable and start services
  systemd: name="httpd" enabled=yes state=started
