---
- name: Add the docker repo to yum
  copy: src="docker.repo" dest="/etc/yum.repos.d/docker.repo"

- name: Install the Docker daemon on all nodes
  yum: name=docker-engine state=present

- name: Enable and start the docker daemon on all nodes
  systemd:
    name: docker
    state: started
    enabled: yes
    
