---
- name: Install required packages to build ganglia
  yum: name="{{ item }}" state=present
  with_items:
    - rsync
    - tar
    - apr-devel
    - rrdtool-devel
    - libconfuse-devel
    - pcre-devel
    - expat-devel
    - gcc
    - zlib-devel
    - make
    - php
    - httpd

- name: Add the ganglia group
  group:
    name: ganglia
    state: present

- name: Add the ganglia user
  user:
    name: ganglia
    group: ganglia
    state: present
    createhome: no

- name: Get ganglia source
  get_url: dest="/tmp" url="{{ ganglia_url }}"

- name: Extract source
  shell: tar -zxf "{{ ganglia_pkg_full }}"
  args:
    chdir: "/tmp"

- name: Configure, compile, install
  shell: "{{ item }}"
  with-items:
    - ./configure --with-gmetad
    - make -j{{ headnode_cores }}
    - make install
  args:
    chdir: "{{ ganglia_build_dir }}"
