---
- name: Ensure EPEL is enabled
  yum: name="epel-release" state=present

- name: Install the ganglia monitoring daemon
  yum: name="{{ item }}" state=present
  with_items:
    - ganglia-gmond
    - ganglia-gmond-python

- name: Copy the correct configs
  copy: src="gmond.conf" dest="//etc/ganglia/gmond.conf"

- name: Enable the monitoring daemon
  systemd:
    name: gmond
    enabled: yes
