---
# Installing torque. This could probably be improved

- hosts: localhost
  user: root
  roles:
    - torque

- hosts: compute_nodes
  user: root
  tasks:
    - include: roles/torque/tasks/computenode.yml
