---
# Installing torque. This could probably be improved
- hosts: compute_nodes
  user: root
  pre_tasks:
    - include: roles/torque/tasks/main.yml
      delegate_to: head.cluster
      connection: local
      run_once: true
  tasks:
    - include: roles/torque/tasks/computenode.yml
  post_tasks:
    - include: roles/torque/tasks/post.yml
      delegate_to: head.cluster
      run_once: true

# Install openmpi
- hosts: localhost
  user: root
  roles:
    - openmpi

# Install Ganglia
- hosts: all_nodes
  user: root
  roles:
    - ganglia

- hosts: localhost
  user: root
  tasks:
    - include: roles/ganglia/tasks/head.yml
    
- hosts: compute_nodes
  user: root
  tasks:
    - include: roles/ganglia/tasks/compute.yml
