---
- name: Install deps required for certain benchmarks on all nodes
  yum: name="{{ item }}" state=present
  with_items:
    - atlas
    - atlas-devel
    - lapack
    - lapack-devel
    - lapack64
    - lapack64-devel
    - scalapack-common
    - scalapack-openmpi
    - scalapack-openmpi-devel
    - scalapack-mpich
    - scalapack-mpich-devel
    - time

- name: Adjust values for memory lock limits
  shell: "printf '*            hard   memlock           unlimited\n*            soft    memlock           unlimited\n' >> /etc/security/limits.conf"

- name: Install dependencies for a bunch of apps to be installed
  yum: name="{{ item }}" state=present
  with_items:
    - gtk2
    - gtk3
    - kernel-devel

- name: Do some general optimizations
  shell: "{{ item }}"
  with_items:
    - echo 'fs.file-max=6544018' >> /etc/sysctl.conf
    - echo 'net.core.somaxconn=512' >> /etc/sysctl.conf

- name: Add nfs shares home to the FSTAB of the compute nodes
  lineinfile: dest=/etc/fstab line="{{ head_internal_ip }}:/home /home nfs rw,sync,hard,intr 0 0"

- name: Mount the new directories on the compute nodes
  shell: mount -a
