---
- name: Copy over torque child services
  copy: src={{ torque_compile_dir }}/{{ item }} dest=/tmp/
  with_items: "{{ torque_client_packages }}"

- name: Copy over the systemd services
  copy: src={{ torque_compile_dir }}/contrib/systemd/pbs_mom.service dest=/usr/lib/systemd/system/

- name: Install the services on the compute nodes
  shell: sh /tmp/{{ item }} --install
  with_items: "{{ torque_client_packages }}"

- name: Write lib for compute
  shell: "echo '/usr/local/lib' > /etc/ld.so.conf.d/torque.conf"

- name: Run library config binary on compute nodes
  shell: /sbin/ldconfig

- name: Set compute nodes to use head node as server_name
  shell: echo "{{ head_fqdn }}" > /var/spool/torque/server_name

- name: Enable and start the PBS_MOM service
  systemd:
    name: pbs_mom
    enabled: yes
    state: started
